spring.application.name=steam-stats

# Serveur
server.port=${PORT:8080}

# Configuration Steam
steam.api.key=${API_KEY_STEAM}
steam.api.base-url=https://api.steampowered.com

# Session
server.servlet.session.timeout=30m

# Thymeleaf (cache off en dev)
spring.thymeleaf.cache=false

# Connection à Supabase PostgreSQL
spring.datasource.url=${DATABASE_URL}
# Driver JDBC
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=10000

# Pour JPA/Hibernate (optionnel mais recommandé)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=never