spring.application.name=steam-stats

# Serveur
server.port=${PORT:8080}

# Configuration Steam
steam.api.key=${API_KEY_STEAM}
steam.api.base-url=https://api.steampowered.com

# Session
server.servlet.session.timeout=30m

# Thymeleaf
spring.thymeleaf.cache=false

# Connection PostgreSQL - Utilisation des variables natives Railway
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=require
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=10000

# JPA/Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Désactive l'initialisation des scripts SQL
spring.sql.init.mode=never